version: "3"

services:
  loadbalancer:
    image: nginx:latest
    container_name: nginx_loadbalancer
    ports:
      - "5000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web1
      - web2

  web1:
    build:
      context: ./web1
    container_name: web1

  web2:
    build:
      context: ./web2
    container_name: web2
